// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtCs9XFu6n_47kFJ-ZIzcQ55B4Mq4HEwg',
    appId: '1:665440338027:web:0ef1fb20698cc864a8712e',
    messagingSenderId: '665440338027',
    projectId: 'flexdiet-c2d11',
    authDomain: 'flexdiet-c2d11.firebaseapp.com',
    storageBucket: 'flexdiet-c2d11.firebasestorage.app',
    measurementId: 'G-1NJJ4W9QW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJ9j-78VyemiPGHe7Mr5rryvi-ZGqaqE',
    appId: '1:665440338027:android:925baa4408ce4c1ea8712e',
    messagingSenderId: '665440338027',
    projectId: 'flexdiet-c2d11',
    storageBucket: 'flexdiet-c2d11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4WgemB_srPKUQlOnMnwR4CURpUoB9us4',
    appId: '1:665440338027:ios:c3f9a5880fa8f4a6a8712e',
    messagingSenderId: '665440338027',
    projectId: 'flexdiet-c2d11',
    storageBucket: 'flexdiet-c2d11.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlexdiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4WgemB_srPKUQlOnMnwR4CURpUoB9us4',
    appId: '1:665440338027:ios:c3f9a5880fa8f4a6a8712e',
    messagingSenderId: '665440338027',
    projectId: 'flexdiet-c2d11',
    storageBucket: 'flexdiet-c2d11.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlexdiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtCs9XFu6n_47kFJ-ZIzcQ55B4Mq4HEwg',
    appId: '1:665440338027:web:1d05a568b9cead60a8712e',
    messagingSenderId: '665440338027',
    projectId: 'flexdiet-c2d11',
    authDomain: 'flexdiet-c2d11.firebaseapp.com',
    storageBucket: 'flexdiet-c2d11.firebasestorage.app',
    measurementId: 'G-8Y76KQDP20',
  );

}